export const JUZ_DATA = [
  { juz: 1, surah: 1, ayah: 1, surahName: "Al-Fatihah" },
  { juz: 2, surah: 2, ayah: 142, surahName: "Al-Baqarah" },
  { juz: 3, surah: 2, ayah: 253, surahName: "Al-Baqarah" },
  { juz: 4, surah: 3, ayah: 93, surahName: "Ali 'Imran" },
  { juz: 5, surah: 4, ayah: 24, surahName: "An-Nisa" },
  { juz: 6, surah: 4, ayah: 148, surahName: "An-Nisa" },
  { juz: 7, surah: 5, ayah: 82, surahName: "Al-Ma'idah" },
  { juz: 8, surah: 6, ayah: 111, surahName: "Al-An'am" },
  { juz: 9, surah: 7, ayah: 88, surahName: "Al-A'raf" },
  { juz: 10, surah: 8, ayah: 41, surahName: "Al-Anfal" },
  { juz: 11, surah: 9, ayah: 93, surahName: "At-Tawbah" },
  { juz: 12, surah: 11, ayah: 6, surahName: "Hud" },
  { juz: 13, surah: 12, ayah: 53, surahName: "Yusuf" },
  { juz: 14, surah: 15, ayah: 1, surahName: "Al-Hijr" },
  { juz: 15, surah: 17, ayah: 1, surahName: "Al-Isra" },
  { juz: 16, surah: 18, ayah: 75, surahName: "Al-Kahf" },
  { juz: 17, surah: 21, ayah: 1, surahName: "Al-Anbya" },
  { juz: 18, surah: 23, ayah: 1, surahName: "Al-Mu'minun" },
  { juz: 19, surah: 25, ayah: 21, surahName: "Al-Furqan" },
  { juz: 20, surah: 27, ayah: 56, surahName: "An-Naml" },
  { juz: 21, surah: 29, ayah: 46, surahName: "Al-'Ankabut" },
  { juz: 22, surah: 33, ayah: 31, surahName: "Al-Ahzab" },
  { juz: 23, surah: 36, ayah: 28, surahName: "Ya-Sin" },
  { juz: 24, surah: 39, ayah: 32, surahName: "Az-Zumar" },
  { juz: 25, surah: 41, ayah: 47, surahName: "Fussilat" },
  { juz: 26, surah: 46, ayah: 1, surahName: "Al-Ahqaf" },
  { juz: 27, surah: 51, ayah: 31, surahName: "Adh-Dhariyat" },
  { juz: 28, surah: 58, ayah: 1, surahName: "Al-Mujadila" },
  { juz: 29, surah: 67, ayah: 1, surahName: "Al-Mulk" },
  { juz: 30, surah: 78, ayah: 1, surahName: "An-Naba" }
];

export const HIZB_DATA = [
  { hizb: 1, surah: 1, ayah: 1, surahName: "Al-Fatihah" },
  { hizb: 2, surah: 2, ayah: 75, surahName: "Al-Baqarah" },
  { hizb: 3, surah: 2, ayah: 142, surahName: "Al-Baqarah" },
  { hizb: 4, surah: 2, ayah: 203, surahName: "Al-Baqarah" },
  { hizb: 5, surah: 2, ayah: 253, surahName: "Al-Baqarah" },
  { hizb: 6, surah: 3, ayah: 15, surahName: "Ali 'Imran" },
  { hizb: 7, surah: 3, ayah: 93, surahName: "Ali 'Imran" },
  { hizb: 8, surah: 3, ayah: 171, surahName: "Ali 'Imran" },
  { hizb: 9, surah: 4, ayah: 24, surahName: "An-Nisa" },
  { hizb: 10, surah: 4, ayah: 88, surahName: "An-Nisa" },
  { hizb: 11, surah: 4, ayah: 148, surahName: "An-Nisa" },
  { hizb: 12, surah: 5, ayah: 27, surahName: "Al-Ma'idah" },
  { hizb: 13, surah: 5, ayah: 82, surahName: "Al-Ma'idah" },
  { hizb: 14, surah: 6, ayah: 36, surahName: "Al-An'am" },
  { hizb: 15, surah: 6, ayah: 111, surahName: "Al-An'am" },
  { hizb: 16, surah: 6, ayah: 141, surahName: "Al-An'am" },
  { hizb: 17, surah: 7, ayah: 88, surahName: "Al-A'raf" },
  { hizb: 18, surah: 7, ayah: 171, surahName: "Al-A'raf" },
  { hizb: 19, surah: 8, ayah: 41, surahName: "Al-Anfal" },
  { hizb: 20, surah: 9, ayah: 34, surahName: "At-Tawbah" },
  { hizb: 21, surah: 9, ayah: 93, surahName: "At-Tawbah" },
  { hizb: 22, surah: 10, ayah: 26, surahName: "Yunus" },
  { hizb: 23, surah: 11, ayah: 6, surahName: "Hud" },
  { hizb: 24, surah: 11, ayah: 84, surahName: "Hud" },
  { hizb: 25, surah: 12, ayah: 53, surahName: "Yusuf" },
  { hizb: 26, surah: 13, ayah: 19, surahName: "Ar-Ra'd" },
  { hizb: 27, surah: 15, ayah: 1, surahName: "Al-Hijr" },
  { hizb: 28, surah: 16, ayah: 51, surahName: "An-Nahl" },
  { hizb: 29, surah: 17, ayah: 1, surahName: "Al-Isra" },
  { hizb: 30, surah: 17, ayah: 99, surahName: "Al-Isra" },
  { hizb: 31, surah: 18, ayah: 75, surahName: "Al-Kahf" },
  { hizb: 32, surah: 19, ayah: 58, surahName: "Maryam" },
  { hizb: 33, surah: 21, ayah: 1, surahName: "Al-Anbya" },
  { hizb: 34, surah: 22, ayah: 1, surahName: "Al-Hajj" },
  { hizb: 35, surah: 23, ayah: 1, surahName: "Al-Mu'minun" },
  { hizb: 36, surah: 24, ayah: 21, surahName: "An-Nur" },
  { hizb: 37, surah: 25, ayah: 21, surahName: "Al-Furqan" },
  { hizb: 38, surah: 26, ayah: 111, surahName: "Ash-Shu'ara" },
  { hizb: 39, surah: 27, ayah: 56, surahName: "An-Naml" },
  { hizb: 40, surah: 28, ayah: 51, surahName: "Al-Qasas" },
  { hizb: 41, surah: 29, ayah: 46, surahName: "Al-'Ankabut" },
  { hizb: 42, surah: 30, ayah: 31, surahName: "Ar-Rum" },
  { hizb: 43, surah: 33, ayah: 31, surahName: "Al-Ahzab" },
  { hizb: 44, surah: 34, ayah: 24, surahName: "Saba" },
  { hizb: 45, surah: 36, ayah: 28, surahName: "Ya-Sin" },
  { hizb: 46, surah: 37, ayah: 145, surahName: "As-Saffat" },
  { hizb: 47, surah: 39, ayah: 32, surahName: "Az-Zumar" },
  { hizb: 48, surah: 40, ayah: 41, surahName: "Ghafir" },
  { hizb: 49, surah: 41, ayah: 47, surahName: "Fussilat" },
  { hizb: 50, surah: 42, ayah: 51, surahName: "Ash-Shuraa" },
  { hizb: 51, surah: 46, ayah: 1, surahName: "Al-Ahqaf" },
  { hizb: 52, surah: 48, ayah: 18, surahName: "Al-Fath" },
  { hizb: 53, surah: 51, ayah: 31, surahName: "Adh-Dhariyat" },
  { hizb: 54, surah: 54, ayah: 55, surahName: "Al-Qamar" },
  { hizb: 55, surah: 58, ayah: 1, surahName: "Al-Mujadila" },
  { hizb: 56, surah: 61, ayah: 1, surahName: "As-Saf" },
  { hizb: 57, surah: 67, ayah: 1, surahName: "Al-Mulk" },
  { hizb: 58, surah: 72, ayah: 1, surahName: "Al-Jinn" },
  { hizb: 59, surah: 78, ayah: 1, surahName: "An-Naba" },
  { hizb: 60, surah: 87, ayah: 1, surahName: "Al-A'la" }
];